---
title: "C Index"
author: "Daniel Ahn"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

Here, we used the hmisc package in R to estimate the Harell's c-indices for laboratory and allocation MELD/PELD scores in rank-ordering candidates by pre-transplant mortality risk. 


```{r c_index}

#allocation_c_boostrap is the function for determining the c-index of allocation MELD/PELD.
allocation_c_bootstrap <- function(test_cohort, indices){
  test_data <- test_cohort[indices,]
  return(rcorr.cens(-1 * (test_data$SCORE), Surv(test_data$SURVIVAL_TIME, test_data$DEATH))["C Index"])
}

set.seed(1)
allocation_c <- boot(data=p1, statistic=allocation_c_bootstrap, R=250)
print(mean(allocation_c$t))

boot.ci(boot.out=allocation_c, type=c("norm","perc","basic"))

#laboratory_c_boostrap is the function for determining the c-index of laboratory MELD/PELD.
laboratory_c_bootstrap <- function(test_cohort, indices){
  test_data <- test_cohort[indices,]
  return(rcorr.cens(-1 * (test_data$LAB_SCORE), Surv(test_data$SURVIVAL_TIME, test_data$DEATH))["C Index"])
}

set.seed(1)
laboratory_c <- boot(data=p1, statistic=laboratory_c_bootstrap, R=250)
print(mean(laboratory_c$t))

boot.ci(boot.out=laboratory_c, type=c("norm","perc","basic"))

```
